version: 3

images:
  base_image:
    name: quay.io/rockylinux/rockylinux:10
dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - google-auth
  galaxy:
    collections:
    - name: google.cloud
  
  system:
    - openssh-clients
    - sshpass

additional_build_steps:
  prepend_base:
    - ENV ANSIBLE_HOST_KEY_CHECKING=False
