---
- name: Create new instance
  hosts: localhost
  gather_facts: no

  vars:
    suffix: ansible-test-1
    service_account_file: "/{{ proj_root }}/secrets/outbreak-info-h5n1-4327e2e241a0.json"
    project: outbreak-info-h5n1
    network_name: muninn-network
    zone: us-central1-c
    machine_type: e2-highcpu-8
    network_tags:
      - http-server
      - lb-health-check
      - muninn

  tasks:
    - name: Create disk
      google.cloud.gcp_compute_disk:
        name: "boot-disk-{{ suffix }}"
        source_image: projects/debian-cloud/global/images/family/debian-12
        size_gb: 32
        project: "{{ project }}"
        zone: "{{ zone }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present
      register: boot_disk


    - name: Create instance
      google.cloud.gcp_compute_instance:
        name: "muninn-h5n1-{{ suffix }}"
        machine_type: "{{ machine_type }}"
        project: "{{ project }}"
        zone: "{{ zone }}"
        disks:
          source: "{{ boot_disk }}"
          auto_delete: 'true'
          boot: 'true'
        network_interfaces:
          - network: "{{ network_name }}"
        tags:
          items: "{{ network_tags }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present

