---
- name: Create new instance
  hosts: localhost
  gather_facts: no

  vars:
    proj_root: /muninn
    # the prefix is "muninn-"
    suffix: "h5n1-16-mar"
    service_account_file: "/{{ proj_root }}/secrets/outbreak-info-h5n1-4327e2e241a0.json"
    project: outbreak-info-h5n1
    network_name: muninn-network
    zone: us-central1-c
    machine_type: c4-highcpu-8
    disk_type: hyperdisk-balanced
    network_tags:
      - http-server
      - lb-health-check
      - muninn

  tasks:
    - name: Create disk
      google.cloud.gcp_compute_disk:
        name: "boot-disk-{{ suffix }}"
        source_image: projects/debian-cloud/global/images/family/debian-12
        size_gb: 32
        type: "{{ disk_type }}"
        project: "{{ project }}"
        zone: "{{ zone }}"
        state: present
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
      register: boot_disk

    - name: Get network info
      google.cloud.gcp_compute_network_info:
        filters:
          - name = "{{ network_name }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
      register: network_info

    - name: Create instance
      google.cloud.gcp_compute_instance:
        name: "muninn-{{ suffix }}"
        machine_type: "{{ machine_type }}"
        project: "{{ project }}"
        zone: "{{ zone }}"
        disks:
          - source: "{{ boot_disk }}"
            auto_delete: 'true'
            boot: 'true'
        network_interfaces:
          - network: 
              selfLink: "{{ network_info.resources[0].selfLink }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        tags:
          items: "{{ network_tags }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present
