- name: Print uptime
  hosts: '{{ target_hosts }}'
  gather_facts: no

  tasks:
    - name: Run uptime
      ansible.builtin.shell: uptime
      register: uptime_result

    - name: Print output
      ansible.builtin.debug:
        var: uptime_result.stdout
